sudo: required
dist: xenial
language: generic

env:
  global:
    - ROS_DISTRO=kinetic
    - UPSTREAM-WORKSPACE=file
    - ROSINSTALL_FILENAME=.travis.rosinstall
    - WRITABLE_SOURCE=true

before_install:
    - git clone https://github.com/clearpathrobotics/occupancy_grid_utils
    - git submodule update --init --remote --recursive

install:
  - git clone --depth=1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci
script:
  - .industrial_ci/travis.sh
