# Site settings
title: ROSPlan by KCL Planning
email: michael.cashmore@kcl.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  ROSPlan is a framework for PDDL planning in a ROS system.
  ROSPlan integrates Artificial Intelligence Planning into Robotics.

# online settings
# baseurl: "/ROSPlan/"
# url: "https://KCL-Planning.github.io/ROSPlan"

# offline settings
# baseurl: ""
# url: "http://localhost:4000"

baseurl: "/ROSPlan/"
url: "https://KCL-Planning.github.io/ROSPlan"

include: ['_pages']

collections:
  documentation:
    output: true
  tutorials:
    output: true
  demos:
    output: true

# Build settings
markdown: kramdown
highlighter: rouge
